import { merriweatherSans } from '@/app/ui/fonts';
import "./globals.css";
import Navbar from './ui/Navbar';
import Footer from './ui/Footer';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={ merriweatherSans.className }
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
